<?php

namespace PMPBundle\Repository;

/**
 * CargoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CargoRepository extends \Doctrine\ORM\EntityRepository
{
    public function buscarPorId($id) {

        try {
            $sql = $this->createQueryBuilder('c')
                ->select('c')
                ->andWhere('c.id = :id')
                ->setParameter('id', $id);

            $result= $sql->getQuery()->getSingleResult();
            return $result;

        } catch(\Exception $e){

            return null;
        }
    }
}
