<?php

namespace PMPBundle\Repository;

/**
 * CargoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CentroCustoRepository extends \Doctrine\ORM\EntityRepository
{
}
