<?php

namespace PMPBundle\Repository;

/**
 * ContaPatrimonialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContaPatrimonialRepository extends \Doctrine\ORM\EntityRepository
{
}
