<?php

namespace PMPBundle\Repository;

/**
 * ContaPatrimonialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContaPatrimonialRepository extends \Doctrine\ORM\EntityRepository
{
    public function buscarPorId($id, $nome)
    {
        $nomelike = strtoupper($nome);

        try {
            $sql = $this->createQueryBuilder('cp')
                ->select('cp');

            if ($id != '') {
                $sql->andWhere('cp.id = :id');
                $sql->setParameter('id', $id);
            }
            if ($nome != '') {
                $sql->andWhere($sql->expr()->like('cp.nome', ':nomelike'));
                $sql->setParameter('nomelike', "%{$nomelike}%");
            }
            $sql->andWhere('cp.status = 1');
            $result = $sql->getQuery()->getResult();
            return $result;

        } catch (\Exception $e) {

            return null;
        }
    }
}
