<?php

namespace PMPBundle\Repository;

/**
 * ContaPatrimonialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContaPatrimonialRepository extends \Doctrine\ORM\EntityRepository
{
    public function buscarPorId($id) {

        try {
            $sql = $this->createQueryBuilder('cp')
                ->select('cp')
                ->andWhere('cp.id = :id')
                ->setParameter('id', $id);

            $result= $sql->getQuery()->getResult();
            return $result;

        } catch(\Exception $e){

            return null;
        }
    }
}
