<?php

namespace PMPBundle\Repository;

/**
 * EstabelecimentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstabelecimentoRepository extends \Doctrine\ORM\EntityRepository
{
}
