<?php

namespace PMPBundle\Repository;

/**
 * CargoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatrimonioRepository extends \Doctrine\ORM\EntityRepository
{
    public function buscar($plaqueta, $descricao)
    {
        $plaquetalike = strtoupper($plaqueta);
        $nomelike = strtoupper($descricao);

        try {

            $sql = $this->createQueryBuilder('p')
                ->select('p');

            if ($plaqueta != '') {
                $sql->andWhere($sql->expr()->like('p.plaqueta', ':plaquetalike'));
                $sql->setParameter('plaquetalike', "%{$plaquetalike}%");
            }

            if ($descricao != '') {
                $sql->andWhere($sql->expr()->like('p.nopatrimonio', ':nomelike'));
                $sql->setParameter('nomelike', "%{$nomelike}%");
            }

            $sql->andWhere('p.situacao != 4');

            /**$sql->andWhere('p.situacao = 4');**/

            $result = $sql->getQuery()->getResult();

            return $result;

        } catch (\Exception $e) {

            return null;
        }
    }

    public function patrimonioPorSituacao($centroCusto)
    {
        $sql = $this->createQueryBuilder('p')
            ->select('p.situacao as situacao,count(p.id) as quant');

            if($centroCusto != ''){
                $sql->andWhere('p.centroDeCusto = :centroCusto');
                $sql->setParameter('centroCusto',$centroCusto);
            }

        $sql->groupBy('p.situacao');

        $result = $sql->getQuery()->getResult();

        return $result;
    }

    public function patrimonioContaPatrimonial()
    {
        $sql = $this->createQueryBuilder('p')
            ->select('cp.id as id, cp.nome as nome,count(p.id) as quant')
            ->join('p.contaPatrimonial', 'cp')
            ->groupBy('cp.id');

        $result = $sql->getQuery()->getResult();

        return $result;
    }

}
