<?php

namespace PMPBundle\Repository;

/**
 * SetorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SetorRepository extends \Doctrine\ORM\EntityRepository
{
}
