<?php

namespace PMPBundle\Repository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends \Doctrine\ORM\EntityRepository
{
    public function buscarPorNome($login) {

        try {
            $sql = $this->createQueryBuilder('u')
                ->select('u')
                ->andWhere('u.userName = :login')
                ->setParameter('login', $login);

            $result= $sql->getQuery()->getSingleResult();

            return $result;

        } catch(\Exception $e){

            return null;
        }
    }
}
